### ISSUE TITLE
[Issue] Stack with id does not exist

### ISSUE THREAD

**Issue by Necromancerx** [nicka/serverless-plugin-diff#15] opened 2019-10-16 03:17 UTC
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command prune
Serverless: Load command diff
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke diff
Serverless: Downloading currently deployed template
 
 Exception -----------------------------------------------
 
  'Stack with id xxxxxxxxx does not exist'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              8.9.1
     Framework Version:         1.51.0
     Plugin Version:            1.3.10
     SDK Version:               2.1.0

**Comment by dennisvink** [comment] 2019-11-10 11:19
Seems evident that you can't diff a stack that does not exist. The diff as such is your entire local file.

**Comment by nicka** [comment] 2019-11-11 04:15
@Necromancerx closing as what @dennisvink mentioned, not a bug 😉

**Closed** 2019-11-11 04:14 UTC
